ROR-service/config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  
  root 'pages#index'
 

  resources(:users, only: %i[new show create])
  resources(:user_deposits, only: %i[index create destroy])
  resources(:session, only: %i[new create destroy])

  get('user_deposits_new/:id', to: 'user_deposits#new', as: 'user_deposits_new')
  get('user_all_deposits', to: 'user_deposits#user_all_deposits', as: 'user_all_deposits')
  get('calculate_deposit', to: 'user_deposits#show', as: 'calculate_deposit')
  
  # Defines the root path route ("/")
  # root "posts#index"
end

ROR-service/app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: session_params[:email])
    

    if @user.present? && @user.authenticate(session_params[:password])
      @user.remember_me
      #user_attributes = @user.attributes.transform_keys(&:to_sym).slice(:id, :name, :email)
      user_attributes = @user.attributes.slice('id', 'name', 'email', 'remember_token_digest')
      r_connect.setex(@user.remember_token, 1000 , user_attributes.to_json)

      session[:user_id] = @user.remember_token
      redirect_to(root_path)
    else
      render(:new)
    end

  end

  def destroy
    #debugger 
    #r_connect.del(current_user.remember_token)
    r_delete_remember_token_user
    user_compliete_session
    redirect_to(root_path)    
  end


  private

  def session_params
    params.require(:user).permit(:email, :password)
  end

  def user_exits
    if user_signed_in? then
      redirect_to(root_path)
    end
  end
  
end

ROR-service/app/views/session/new.html.erb
<% provide(:title_name, 'session') %>
<% render_navbar %>

<h1>Session#new</h1>
<p>Find me in app/views/session/new.html.erb</p>

<%= form_with(model: @user, method: 'POST', url: session_index_path, data: { turbo: false }) do |f| %>
	<div class="form">
		<div class="form-group">
			<%= f.label(:email)  %>
		</div>

		<div class="form-group">
			<%=f.text_field(:email, palaceholder: 'email', class: 'form-input')  %>
		</div>

		<div class="form-group">
			<%= f.label(:password)  %>
		</div>

		<div class="form-group">
			<%= f.password_field(:password, class: 'form-input')  %>
		</div>

		<div class="form-group">			
			<%= f.submit('sign_up', class: "btn")  %>
		</div>
		
	</div>
<% end %>