ROR-service/config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  
  root 'pages#index'
 

  resources(:users, only: %i[new show create])
  resources(:user_deposits, only: %i[index create destroy])
  resources(:session, only: %i[new create destroy])

  get('user_deposits_new/:id', to: 'user_deposits#new', as: 'user_deposits_new')
  get('user_all_deposits', to: 'user_deposits#user_all_deposits', as: 'user_all_deposits')
  get('calculate_deposit', to: 'user_deposits#show', as: 'calculate_deposit')
  
  # Defines the root path route ("/")
  # root "posts#index"
end

ROR-service/app/views/shared/_footer.html.erb
<div class="footer-section-1">
	<article class="footer-container-content">
		<div>			
			<div class="footer-name-head text-size-l">
				<span>Навигация</span>
			</div>
			<div class="footer-links-list">
				<ul>
					<li><%= link_to('Категории', url: '#') %></li>
					<li><%= link_to('Сервисы', url: '#') %></li>
					<li><%= link_to('Регистрация', url: '#') %></li>
					<li><%= link_to('Вход', url: '#' ) %></li>
					
				</ul>
			</div>
		</div>
	</article>
</div>

<div class="footer-section-2">
	<article class="footer-container-content">
		<div>
			<div class="footer-name-head text-size-l">
				<span>Контакты</span>
			</div>
			<section class="footer-info-container">					
				<div>
					<div class="footer-info-head">
						<span>Номер отдела:</span>
					</div>
					<div>
						<span> 88003553535</span>						
					</div>
				</div>
				<div>
					<div class="footer-info-head">
						<span>Почта отдела:</span>						
					</div>
					<div>
						<span>supprot@test.com</span>
					</div>
				</div>
			</section>
		</div>	
	</article>
</div>

<div class="footer-section-3">
	<article class="footer-container-content">	
		<div>
			<div class="footer-name-head text-size-l">
				<span>Автор</span>
			</div>
			
			<div>
			<section class="footer-info-container">					
				<div>
					<div class="footer-info-head">
						<span>почта:</span>
					</div>
					<div>
						<span>
							<a href="mailto:Larionov01996@gmail.com" class="footer-link-section-3">Larionov01996@gmail.com</a>
						</span>
					</div>
				</div>
				<div>
					<div class="footer-info-head">
						<span>Github:</span>						
					</div>
					<div>
						<span>
							<a href="https://github.com/RikersMax" class="footer-link-section-3">https://github.com/RikersMax</a>
						</span>
					</div>
				</div>
			</section>
				

			</div>
		</div>
	</article>
</div>

ROR-service/app/views/shared/_info_deposit.html.erb
<div class="service-desc">							
	<div class="row-desc">
		<span>
			id вклада
		</span>
		<span>
			<%= dep['id']  %>										
		</span>
	</div>
		
	<div class="row-desc">
		<span>
			Группа
		</span>
		<span>
			<%= dep['group_name']  %>
		</span>
	</div>

	<div class="row-desc">
		<span>
			Название
		</span>
		<span>
			
			<%= dep['title_vklad'] %>
		</span>
	</div>

	<div class="row-desc">
		<span>
			Ставка
		</span>
		<span>
			
			<%= dep['rate'] %>			
		</span>
	</div>

	<div class="row-desc">
		<span>
			Минимальная сумма
		</span>
		<span>
			
			<%= dep['minimum_currency']  %>
		</span>
	</div>

	<div class="row-desc">
		<span>
			Месяцев
		</span>
		<span>
			
			<% if dep['month']  == 999 then %>
				Неограниченно
			<% else %>
				<%= dep['month'] %>
			<% end %>

		</span>
	</div>

	<div class="row-desc">
		<span>
			Пополнение
		</span>
		<span>
			<%= dep['deposit']  %>
		</span>
	</div>

	<div class="row-desc">
		<span>
			Снятие
		</span>
		<span>
			<%= dep['withdrawal']  %>
		</span>
	</div>
	
	<div class="row-desc-link">
		<% unless hid then %>
			<%= link_to("Рассчитать", url ||= user_deposits_new_path("#{key_bank.to_s}:#{dep['id']}"))  %>
		<% end %>		
	</div>

</div>
	

ROR-service/app/views/shared/_message.html.erb
<div class="message-container">
	<%= flash[:message] %>
</div>

ROR-service/app/views/shared/_navbar.html.erb
<%= provide(:nav_bar) do %>

<article class="nav-bar-container">
	<section class="nav-bar-logo">
		<div class="nav-logo">
			<%= link_to(root_path) do %>
				<div id="container-logo">					
					<%= image_tag('logo/logo.png', size: "50x50") %>
					<div id="text-logo">
						<span>Депозитный</span>
						<span>Калькулятор</span>
					</div>
				</div>	
			<% end %>										
		</div>
	</section>

	<section class="nav-bar-links">
		<div class="nav-links">
			<ul>
				<li><%= link_to(t('nav_bar.links.1_link'), user_deposits_path ) %></li>
				<li><%= link_to(t('nav_bar.links.2_link'), calculate_deposit_path) %></li>			
			</ul>
			
		</div>
	</section>

	<section class="nav-bar-login">
		<div class="nav-login">
			<% if user_signed_in? then %>
			<div class="menu-user-name">
			
				<%= content_tag(:span, current_user.name, class: '') %>
				<div class="dropdown-menu-user">
					
					<ul class="dropdown-menu-ul">
						
						<li><%= link_to(t('user.drop_down_menu.exit'), 
							session_path(current_user.id), 
							data: { turbo_method: :delete }
							) %>		
						</li>
						<hr style="width: 90%;">						
						<li>
							<%= link_to("Мои депозиты", user_all_deposits_path ) %>  
						</li>
						<hr style="width: 90%;">
					</ul>
				</div>
			</div>
			
			<% else %>
				<%= link_to(t('user.drop_down_menu.sign_up'),  new_user_path)  %>
				<hr style="height: 50%; margin: 0 1em;">
				<%= link_to(t('user.drop_down_menu.sign_in'),  new_session_path)  %>
			<% end %>	
		</div>
	</section>
</article>
	

<% end %>